name: Trigger auto deployment for container-app-azazr5k3gk4au

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-azazr5k3gk4au-AutoDeployTrigger-2ca1edc0-10b0-4e5a-a74b-111c85088016.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPAZAZR5K3GK4AU_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPAZAZR5K3GK4AU_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPAZAZR5K3GK4AU_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryazazr5k3gk4au.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPAZAZR5K3GK4AU_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPAZAZR5K3GK4AU_REGISTRY_PASSWORD }}
          containerAppName: container-app-azazr5k3gk4au
          resourceGroup: flaskstarterb06a
          imageToBuild: containerregistryazazr5k3gk4au.azurecr.io/container-app-azazr5k3gk4au:${{ github.sha }}
          


